plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

version = project.mod_version
group = project.maven_group

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
}

loom {
    mods {
        "krispite" {
            sourceSet sourceSets.main
        }
    }

    runs {
        client {
            client()
        }
    }
}

sourceSets {
    main {
        java.srcDir project(':common').sourceSets.main.java
        resources.srcDir project(':common').sourceSets.main.resources
    }
}

processResources {
    def version = project.version
    filesMatching("fabric.mod.json") {
        expand "version": version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    from(rootProject.file("LICENSE"))
}
